# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.15.0-2-ga590b62
_src_path: .
author_email: test@example.com
author_name: Test Author
backend_image_name: ''
backend_jenkins_job: ''
backend_port: 5000
backend_repo_url: ''
frontend_jenkins_job: ''
frontend_port: 3000
image_name: registry:5000/test-app
project_description: Test application
project_name: test-app
project_title: Test App
repo_url: https://github.com/test/test-app.git
sse_gateway_port: 3001
use_app_shell: true
use_oidc: true
use_sse: true
validation_image_name: registry:5000/test-app-validation
validation_jenkins_job: ''
