# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.20.2-1-g9838d5b
_src_path: .
author_email: test@example.com
author_name: Test Author
backend_port: 5000
frontend_port: 3000
project_description: Test application
project_name: test-app
project_title: Test App
sse_gateway_port: 3001
use_app_shell: true
use_oidc: true
use_sse: true
